# Project information

site_name: "PsiOps Field Manual"
site_url: https://joemoose.github.io/psiops/
site_author: Zachary Taylor
site_description: An Action Roleplaying Game of Paranormal Special Forces
site_dir: site/

# Repo

repo_url: https://github.com/joemoose/psiops/
edit_uri: edit/main/docs

# Navigation

nav:
  - index.md
  - character.md
  - playing.md
  - combat.md
  - zones.md
  - stress.md
  - equipment.md
  - appendix.md
  - attribution.md
    
# Theme

theme:
  name: material
  language: en
  font: false
  logo: img/logo.png
  favicon: img/favicon.ico
  icon:
    edit: octicons/pencil-24
  features:
    - content.action.edit
    - content.tooltips
    - header.autohide
    - navigation.footer
    - navigation.instant
    - navigation.top
    - navigation.tracking
    - toc.follow
    
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: black
      scheme: default
      toggle:
        icon: material/brightness-auto
        name: Switch to Light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: black
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to Dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: black
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to System preferences

# Extensions

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - md_in_html
  - pymdownx.snippets:
      base_path: [docs]
  - toc:
      permalink: true
      toc_depth: 3

# CSS

extra_css:
  - css/extra.css
  - css/print.css

# Plugins

plugins:
  - search:
      lang: en
